# backend/report_generator.py

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet
from .calculations import Calculations

class ReportGenerator:
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.calculations = Calculations()
    
    def generate_pdf_report(self, analysis_results):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        story = []
        
        skill_analysis = analysis_results["skill_analysis"]
        compatibility_score = analysis_results['compatibility_score']
        skill_gap = self.calculations.calculate_skill_gap(skill_analysis)
        skill_coverage = self.calculations.calculate_skill_coverage(skill_analysis)
        
        # Title and header
        story.append(Paragraph("Skill Gap Analysis Report", self.styles['Title']))
        story.append(Spacer(1, 10))
        story.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Overall metrics
        story.append(Paragraph("Overall Assessment", self.styles['Heading2']))
        metrics_data = [
            ['Overall Compatibility', f"{compatibility_score:.1f}%"],
            ['Skill Gap', f"{skill_gap:.1f}%"],
            ['Skill Coverage', f"{skill_coverage:.1f}%"]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[200, 100])
        story.append(metrics_table)
        story.append(Spacer(1, 10))
        
        # Assessment message
        assessment = self.calculations.get_assessment_message(compatibility_score)
        story.append(Paragraph(assessment, self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Skill breakdown
        story.append(Paragraph("Skill Breakdown", self.styles['Heading2']))
        breakdown_data = [
            ['High Matches', str(skill_analysis['high_match_count'])],
            ['Partial Matches', str(skill_analysis['partial_match_count'])],
            ['Missing Skills', str(skill_analysis['missing_count'])]
        ]
        
        breakdown_table = Table(breakdown_data, colWidths=[150, 80])
        story.append(breakdown_table)
        story.append(Spacer(1, 20))
        
        # Skills lists
        if skill_analysis['matched_skills']:
            story.append(Paragraph("Your Strong Skills:", self.styles['Heading3']))
            for skill in skill_analysis['matched_skills'][:10]:
                story.append(Paragraph(f"• {skill['job_skill']}", self.styles['Normal']))
            story.append(Spacer(1, 10))
        
        if skill_analysis['partial_matches']:
            story.append(Paragraph("Skills to Improve:", self.styles['Heading3']))
            for skill in skill_analysis['partial_matches'][:10]:
                story.append(Paragraph(f"• {skill['job_skill']}", self.styles['Normal']))
            story.append(Spacer(1, 10))
        
        if skill_analysis['missing_skills']:
            story.append(Paragraph("Skills to Learn:", self.styles['Heading3']))
            for skill in skill_analysis['missing_skills'][:10]:
                story.append(Paragraph(f"• {skill['skill']}", self.styles['Normal']))
        
        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by Skill Gap Analyzer", self.styles['Italic']))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
